.TH TOMBOY-NG 1
.SH NAME 
tomboy-ng \- manage a collection of notes using a simple markup
.SH SYNOPSIS 
.B tomboy-ng
[\fB\-h\fR]
[\fB\-g\fR]
[\fB-\-gnome3\fR]
[\fB\-\-debug\-sync\fR] 
[\fB\-\-debug\-index\fR] 
[\fB\-\-debug-log\fR=\fILOGFILE\fR]
[\fB\-\-lang\fR=\fICC\fR]
[\fB\-\-config\-dir\fR=\fIPATH_to_DIR\fR]
[\fB\-o\fR \fIPATH_to_NOTE\fR] 
[\fB\-\-open-note\fR=\fIPATH_to_NOTE\fR]
[\fIPATH_to_NOTE\fR]

.SH DESCRIPTION
.B tomboy-ng
is a rewrite of the much loved Tomboy Notes. It runs on Linux, Windows and MacOS. It is file compatible with Tomdroid and GNote (>=v0.30). Tomboy-ng notes support Bold, Italic, Strikethrough, Highlight and Underline in four sizes. It will sync notes with other systems using Tomboy's File Sync model and to remote servers using sshfs.

tomboy-ng has built in systems to take snapshots of your notes for safe keeping, to import and export notes in different formats, spell checking means to group your notes into "notebooks" for easy management.

Many users will want to have tomboy-ng start at logon time and leave it running indefinitly. When running, it will put an Icon in the System Tray and you can interact with it via that Icon. However, some Gnome 3 based Linux distros cannot display the System Tray Icon, on such limited systems, add tomboy-ng to your dock as a favourite and clicking that will either start tomboy-ng or activate an existing instance. 

On Windows and Mac tomboy-ng uses native libraries, on Linux, tomboy-ng comes in both GTK2 and Qt5 version and most systems have almost all the necessary libraries pre installed.

While options below are familiar to Linux users, Mac and Windows users may like to look at some examples further down to see how to use them.

.SH OPTIONS
.TP
.BR \-h 
Print some help and exit.

.TP
.BR \-\-debug-sync
Generate a lot of logging information on the console during a sync process. Intended for debugging.

.TP
.BR \-\-debug-index
Generate a lot of logging information on the console while indexing the notes repo. Intended for debugging.

.TP
.BR \-\-debug\-log=\fILOGFILE
Direct debug info to a file, this is necessary to see that output on Windows and Mac and sometimes useful on Linux. LOGFILE is a filename and a (writable) path to that filename. See section below on debugging.

.TP
.BR \-\-lang=\fICC\fR
Tomboy-ng normally picks up its language from the OS and does an auto switch. However, its possible to force a language at startup using the two letter language code, ie es for spanish, nl for dutch.

.TP
.BR \-c ", " \-\-config\-dir=\fIPATH_to_DIR\fR
Create or use an alterative config. That config could, for example, specify an alterative location to store notes and sync against a different file sync repository.

.TP
.BR \-o ", " \-\-open-note=\fIPATH_to_NOTE\fR
Open a note in single note mode. In this mode, a separate process runs, it does not have access to the normal notes location, nor sync but can read, display and write back to a stand alone note. If the note name does not exist, a new note is created. If the note name specifies a plain text file or a rtf file, the contents of that file will be imported into a new note and that note will be named as specified on the command line but with an extension of ".note".  In this mode, the note remains in its existing location, it is not moved to the tomboy-ng notes location, it is not synced, nor searched by tomboy-ng in its normal mode. Note that the switch (-o or --open-note) is optional, "tomboy-ng some.note" will works as well.


.SH Further Help
tomboy-ng comes bundled with several read only notes that provide help on topics such as keyboard short cuts, setting up a sync system, using the built in calculator and keeping your notes safe.

The project's wiki also has extensive information available.
.I https://github.com/tomboy-notes/tomboy-ng


.SH DEBUGGING
tomboy-ng accepts a couple of debug switches as noted above. They will write detailed progress reports relating to their section of the application to the console. However, Windows and Mac do not, for this purpose, have a console. But can be told to capture this log info to a file using another command line switch or by setting an env variable that specifies a file name. Please ensure you have permission to write to the location specified.

tomboy-ng  \-\-debug-log=%userprofile%\\debug.txt  \-\-debug-sync

set tomboy-ng_debuglog=c:\\%userprofile%\\debug.txt

Mac users can do something similar : 

open /Applications/tomboy-ng.app \-\-args     "\-\-debug-log=$HOME/tomboy-ng.log"  "\-\-debug-sync"

Linux users who need a debug logfile can also :

tomboy-ng \-\-debug-sync \-\-debug-log=$HOME/tomboy-ng.log

Windows users should do something like this -

Rightclick the startbutton and select "run".  In the field, enter this command line exactly as show (including the inverted commas) - 

"C:\\Program Files\\tomboy-ng\\tomboy-ng.exe" --debug-index --debug-log=%userprofile%\\Desktop\\tomboy-log.txt

Press enter, tomboy-ng should start up normally. Close it. A file called tomboy-log.txt will have been created on your desktop.

If you intend to post such a log file to (eg) the Tomboy help system, do please check through it first to ensure there is nothing there you don't want the world to see.


.SH "SEE ALSO"
.I https://github.com/tomboy-notes/tomboy-ng

There you will find several wiki pages going into far more detail than here. 

.SH BUGS
Please send bug reports to the Tomboy mailing list
(tomboy-list@beatniksoftware.com) or via Github see above.




